<center>
<img src="../../img/ods_stickers.jpg" />
    
## [mlcourse.ai](https://mlcourse.ai) – Open Machine Learning Course 
Author: Arina Lopukhova (@erynn). Edited by [Yury Kashnitskiy](https://yorko.github.io) (@yorko) and Vadim Shestopalov (@vchulski). This material is subject to the terms and conditions of the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license. Free use is permitted for any non-commercial purpose.

# <center>Assignment #1. Fall 2019
## <center>Exploratory data analysis of Olympic games with Pandas
    
<img src='../../img/olympic_logo.png' width=50%>

Prior to working on the assignment, you'd better check out the corresponding course material:
 - [Exploratory data analysis with Pandas](https://nbviewer.jupyter.org/github/Yorko/mlcourse_open/blob/master/jupyter_english/topic01_pandas_data_analysis/topic1_pandas_data_analysis.ipynb?flush_cache=true), the same as an interactive web-based [Kaggle Kernel](https://www.kaggle.com/kashnitsky/topic-1-exploratory-data-analysis-with-pandas)
 - first lectures in mlcourse.ai [YouTube playlist ](https://www.youtube.com/watch?v=QKTuw4PNOsU&list=PLVlY_7IJCMJeRfZ68eVfEcu-UcN9BbwiX) 
 - you can also practice with demo assignments, which are simpler and already shared with solutions: [A1 demo](https://www.kaggle.com/kashnitsky/a1-demo-pandas-and-uci-adult-dataset), [solution](https://www.kaggle.com/kashnitsky/a1-demo-pandas-and-uci-adult-dataset-solution)

### Your task is to:
 1. write code and perform computations in the cells below
 2. choose answers in the [webform](https://docs.google.com/forms/d/1JxhQ9Bg4OpM3E5N47ZuRbILgDuMRbvEnUbDMZK8L-NU). Solutions will be shared only with those who've filled in this form 
 3. submit answers with some email and **remember it**! This will be your ID during the course. Specify your real full name in the form as well (no nicks allowed in the final top-100 [rating](https://mlcourse.ai/rating)). If in doubt, you can re-submit the form till the deadline for A1, no problem, but stick to only one email.
 
### <center> Deadline for A1: 2019 September 15, 20:59 GMT (London time)
    
You'll get up to 10 credits for this assignment.

### How to get help
In [ODS Slack](https://opendatascience.slack.com) (if you still don't have access, fill in the [form](https://docs.google.com/forms/d/10HAN5huM996snUKjsNYyT_oOlm2uOsTKulKurb3oiNM/) mentioned on the mlcourse.ai main page), we have a channel **#mlcourse_ai_news** with announcements from the course team.
You can discuss the course content freely in the **#mlcourse_ai** channel (we still have a huge Russian-speaking group, they have a separate channel **#mlcourse_ai_rus**).

Here's how you reply in a thread (press this dialog icon to drill down into a thread):

<img src="../../img/start_a_thread.png" />

Please stick to special threads *a1_q1-5_fall2019* and *a1_q6-10_fall2019* in **#mlcourse_ai_news** for your questions on A1. Help each other without sharing correct code and answers. Our TA **Vadim @vchulski** is there to help (only in the mentioned thread, do not write to him directly).

Lastly, you can save useful messages by pinning them, further you can find pinned items on the top, just below the channel name:

<img src="../../img/pinned_item.png" />

### Assignment 
__There are ten questions about 120 years of Olympic history in this task. Your task is to fill in the missing Python code and choose answers in [this web-form](https://docs.google.com/forms/d/1JxhQ9Bg4OpM3E5N47ZuRbILgDuMRbvEnUbDMZK8L-NU).__

Download the file `athlete_events.csv` from [here](https://drive.google.com/file/d/1f5v6Z2ayc7h698FG_98wP5x1Y2zZQeox/view?usp=sharing) (scraped by [rgriffin](https://www.randigriffin.com/) from www.sports-reference.com). The dataset has the following features:

- __ID__ - Unique number for each athlete
- __Name__ - Athlete's name
- __Sex__ - M or F
- __Age__ - Integer
- __Height__ - In centimeters
- __Weight__ - In kilograms
- __Team__ - Team name
- __NOC__ - National Olympic Committee 3-letter code
- __Games__ - Year and season
- __Year__ - Integer
- __Season__ - Summer or Winter
- __City__ - Host city
- __Sport__ - Sport
- __Event__ - Event
- __Medal__ - Gold, Silver, Bronze, or NA

In [10]:
import pandas as pd

In [11]:

import sys

for p in sys.path:
    print(p)
    
#python notebooks have weird paths. Cannot give an absolute path otherwise causes a permission error


/opt/conda/lib/python36.zip
/opt/conda/lib/python3.6
/opt/conda/lib/python3.6/lib-dynload
/opt/conda/lib/python3.6/site-packages
/opt/conda/lib/python3.6/site-packages/IPython/extensions
/notebooks/home/.ipython


In [12]:
# Change the path to the dataset file if needed. 
PATH = '../../data/athlete_events.csv'

In [13]:
data = pd.read_csv(PATH)

In [32]:
data.head()

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

In [35]:
print(data.shape)

(271116, 15)


In [66]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
ID        271116 non-null int64
Name      271116 non-null object
Sex       271116 non-null object
Age       261642 non-null float64
Height    210945 non-null float64
Weight    208241 non-null float64
Team      271116 non-null object
NOC       271116 non-null object
Games     271116 non-null object
Year      271116 non-null int64
Season    271116 non-null object
City      271116 non-null object
Sport     271116 non-null object
Event     271116 non-null object
Medal     39783 non-null object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB
None


In [68]:
data['Sport'].value_counts()

Athletics                38624
Gymnastics               26707
Swimming                 23195
Shooting                 11448
Cycling                  10859
Fencing                  10735
Rowing                   10595
Cross Country Skiing      9133
Alpine Skiing             8829
Wrestling                 7154
Football                  6745
Sailing                   6586
Equestrianism             6344
Canoeing                  6171
Boxing                    6047
Speed Skating             5613
Ice Hockey                5516
Hockey                    5417
Biathlon                  4893
Basketball                4536
Weightlifting             3937
Water Polo                3846
Judo                      3801
Handball                  3665
Art Competitions          3578
Volleyball                3404
Bobsleigh                 3058
Tennis                    2862
Diving                    2842
Ski Jumping               2401
                         ...  
Badminton                 1457
Nordic C

__1. How old were the youngest male and female participants of the 1992 Olympics?__

*For discussions, please stick to [ODS Slack](https://opendatascience.slack.com/), channel #mlcourse_ai_news, pinned thread #a1_q1-5_fall2019*

- 16 and 15
- 14 and 13 
- 13 and 11
- 11 and 12

In [48]:
data[(data['Year']== 1992)&(data['Sex']=='M')].Age.describe()

count    11198.000000
mean        24.955438
std          5.028283
min         11.000000
25%         22.000000
50%         24.000000
75%         27.000000
max         62.000000
Name: Age, dtype: float64

In [50]:
data[(data['Year']== 1992)&(data['Sex']=='F')].Age.describe()

count    5171.000000
mean       22.940437
std         5.198453
min        12.000000
25%        19.000000
50%        23.000000
75%        26.000000
max        53.000000
Name: Age, dtype: float64

The youngest male and female participants in the 1992 Olympics were 11 and 12 years old respectively.

__2. What was the percentage of male basketball players among all the male participants of the 2012 Olympics? Round the answer to the first decimal.__

*Hint:* here and further if needed drop duplicated sportsmen to count only unique ones. 

*For discussions, please stick to [ODS Slack](https://opendatascience.slack.com/), channel #mlcourse_ai_news, pinned thread #a1_q1-5_fall2019*

- 0.2
- 1.5 
- 2.5
- 7.7

In [70]:
data[(data['Year']==2012) & (data['Sex']=='M')].ID.nunique()

5863

In [71]:
data[(data['Year']==2012) & (data['Sex']=='M') & (data['Sport']=='Basketball')].ID.nunique()

144

In [72]:
(144/5863)*100

2.4560805048609926

In [ ]:
The percentage of male basketball players among all male participants in the 2012 Olympics was 2.5 (rounded to one decimal)

__3. What are the mean and standard deviation of height for female tennis players who participated in the 2000 Olympics? Round the answer to the first decimal.__

*For discussions, please stick to [ODS Slack](https://opendatascience.slack.com/), channel #mlcourse_ai_news, pinned thread #a1_q1-5_fall2019*

- 171.8 and 6.5
- 179.4 and 10
- 180.7 and 6.7
- 182.4 and 9.1 

In [77]:
data[(data['Year']==2000)&(data['Sex']=='F')&(data['Sport']=='Tennis')].Height.describe()

count    125.000000
mean     171.792000
std        6.458673
min      150.000000
25%      168.000000
50%      172.000000
75%      176.000000
max      191.000000
Name: Height, dtype: float64

The mean is 171.8 and the standard deviation is 6.5.



__4. Find a sportsman who participated in the 2006 Olympics, with the highest weight among other participants of the same Olympics. What sport did he or she do?__

*For discussions, please stick to [ODS Slack](https://opendatascience.slack.com/), channel #mlcourse_ai_news, pinned thread #a1_q1-5_fall2019*

- Judo
- Bobsleigh 
- Skeleton
- Boxing

In [79]:
data[(data['Year']==2006)].Weight.describe()

count    4366.000000
mean       70.519354
std        12.861560
min        38.000000
25%        61.000000
50%        69.000000
75%        79.000000
max       127.000000
Name: Weight, dtype: float64

In [82]:
data[(data['Year']==2006)&(data['Weight']==127)]

ID               Name Sex   Age  Height  Weight     Team  NOC  \
8102  4476  Patrick R. Antaki   M  41.0   185.0   127.0  Lebanon  LIB   

            Games  Year  Season    City     Sport                    Event  \
8102  2006 Winter  2006  Winter  Torino  Skeleton  Skeleton Men's Skeleton   

     Medal  
8102   NaN

The athelete with the highest weight (127) played Skeleton

__5. How many times did John Aalberg participate in the Olympics held in different years?__

*For discussions, please stick to [ODS Slack](https://opendatascience.slack.com/), channel #mlcourse_ai_news, pinned thread #a1_q1-5_fall2019*

- 0
- 1 
- 2
- 3

In [84]:
data[(data['Name']=='John Aalberg')].groupby('Year').count()

ID  Name  Sex  Age  Height  Weight  Team  NOC  Games  Season  City  \
Year                                                                       
1992   4     4    4    4       4       4     4    4      4       4     4   
1994   4     4    4    4       4       4     4    4      4       4     4   

      Sport  Event  Medal  
Year                       
1992      4      4      0  
1994      4      4      0

He participated in the Olympics in 1992 and 1994 for a total of two times.

__6. How many gold medals in tennis did sportspeople from the Switzerland team win at the 2008 Olympics? Count every medal from every sportsperson.__

*For discussions, please stick to [ODS Slack](https://opendatascience.slack.com/), channel #mlcourse_ai_news, pinned thread #a1_q6-10_fall2019*

- 0
- 1 
- 2
- 3 

In [92]:
print(data.columns)

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
      dtype='object')


In [93]:
data.Medal.value_counts()

Gold      13372
Bronze    13295
Silver    13116
Name: Medal, dtype: int64

In [99]:
data[(data['Year']==2008)&(data['Sport']=='Tennis')&(data['Team']=='Switzerland')].Medal.value_counts()

Gold    2
Name: Medal, dtype: int64

The Switzerland tennis team won 2 gold medals at the 2008 Olympics.

__7. Is it true that Spain won fewer medals than Italy at the 2016 Olympics? Do not consider NaN values in _Medal_ column.__ 

*For discussions, please stick to [ODS Slack](https://opendatascience.slack.com/), channel #mlcourse_ai_news, pinned thread #a1_q6-10_fall2019*

- Yes
- No

In [104]:
data[(data['Year']==2016)&(data['Team']=='Spain')].Medal.value_counts().sum()

43

In [105]:
data[(data['Year']==2016)&(data['Team']=='Italy')].Medal.value_counts().sum()

70

Spain won 43 vs 70 medals for Italy in the 2016 Olympics.

__8. What age category did the fewest and the most participants of the 2008 Olympics belong to?__

*For discussions, please stick to [ODS Slack](https://opendatascience.slack.com/), channel #mlcourse_ai_news, pinned thread #a1_q6-10_fall2019*

- [45-55] and [25-35) correspondingly
- [45-55] and [15-25) correspondingly
- [35-45) and [25-35) correspondingly
- [45-55] and [35-45) correspondingly

In [130]:
def func(row):
    if row['Age'] < 15:
        return '1-15'
    elif (row['Age'] >= 15) & (row['Age'] < 25):
        return '15-25'
    elif (row['Age'] >= 25) & (row['Age'] < 35):
        return '25-35' 
    elif (row['Age'] >= 35) & (row['Age'] < 45):
        return '35-45'
    elif (row['Age'] >= 45) & (row['Age'] < 55):
        return '45-55'
    else:
        return '55+'

data['age_brackets'] = data.apply(func, axis=1)

In [131]:
data.age_brackets.value_counts()

15-25    130057
25-35    110991
35-45     15111
55+       10607
45-55      3273
1-15       1077
Name: age_brackets, dtype: int64

The answer is [45-55] and [15-25) correspondingly

Though 1-15 was not an accepted answer. If NAs trigger the condition < 15 then that may be a false count.


__9. Is it true that there were Summer Olympics held in Atlanta? Is it true that there were Winter Olympics held in Squaw Valley?__

*For discussions, please stick to [ODS Slack](https://opendatascience.slack.com/), channel #mlcourse_ai_news, pinned thread #a1_q6-10_fall2019*

- Yes, Yes
- Yes, No
- No, Yes 
- No, No 

In [134]:
data[data['City']=='Atlanta'].head()

ID                  Name Sex   Age  Height  Weight         Team  NOC  \
32   13    Minna Maarit Aalto   F  30.0   159.0    55.5      Finland  FIN   
92   30      Pepijn Aardewijn   M  26.0   189.0    72.0  Netherlands  NED   
97   33   Mika Lauri Aarnikka   M  28.0   187.0    76.0      Finland  FIN   
100  36  Stefan Remco Aartsen   M  21.0   194.0    78.0  Netherlands  NED   
101  36  Stefan Remco Aartsen   M  21.0   194.0    78.0  Netherlands  NED   

           Games  Year  Season     City     Sport  \
32   1996 Summer  1996  Summer  Atlanta   Sailing   
92   1996 Summer  1996  Summer  Atlanta    Rowing   
97   1996 Summer  1996  Summer  Atlanta   Sailing   
100  1996 Summer  1996  Summer  Atlanta  Swimming   
101  1996 Summer  1996  Summer  Atlanta  Swimming   

                                      Event   Medal age_brackets  
32               Sailing Women's Windsurfer     NaN        25-35  
92   Rowing Men's Lightweight Double Sculls  Silver        25-35  
97          Sailing Men's Two Person Dinghy     NaN        25-35  
100     Swimming Men's 100 metres Butterfly     NaN        15-25  
101     Swimming Men's 200 metres Butterfly     NaN        15-25

In [135]:
data[data['City']=='Squaw Valley'].head()

ID              Name Sex   Age  Height  Weight    Team  NOC        Games  \
83   24  Nils Egil Aaness   M  24.0     NaN     NaN  Norway  NOR  1960 Winter   
84   24  Nils Egil Aaness   M  24.0     NaN     NaN  Norway  NOR  1960 Winter   
113  40   Roald Edgar Aas   M  31.0     NaN     NaN  Norway  NOR  1960 Winter   
114  40   Roald Edgar Aas   M  31.0     NaN     NaN  Norway  NOR  1960 Winter   
115  40   Roald Edgar Aas   M  31.0     NaN     NaN  Norway  NOR  1960 Winter   

     Year  Season          City          Sport  \
83   1960  Winter  Squaw Valley  Speed Skating   
84   1960  Winter  Squaw Valley  Speed Skating   
113  1960  Winter  Squaw Valley  Speed Skating   
114  1960  Winter  Squaw Valley  Speed Skating   
115  1960  Winter  Squaw Valley  Speed Skating   

                                 Event Medal age_brackets  
83      Speed Skating Men's 500 metres   NaN        15-25  
84    Speed Skating Men's 1,500 metres   NaN        15-25  
113   Speed Skating Men's 1,500 metres  Gold        25-35  
114   Speed Skating Men's 5,000 metres   NaN        25-35  
115  Speed Skating Men's 10,000 metres   NaN        25-35

Yes Atlanta for Summer 1996 and Squaw Valley for Winter 1960

__10. What is the absolute difference between the number of unique sports at the 1986 Olympics and 2002 Olympics?__

*For discussions, please stick to [ODS Slack](https://opendatascience.slack.com/), channel #mlcourse_ai_news, pinned thread #a1_q6-10_fall2019*

- 3 
- 10
- 15
- 27 

In [141]:
data[data['Year']==1986].Sport.nunique() - data[data['Year']==2002].Sport.nunique()

-15

15 is the absolute difference!

That's it! Now go and do 30 push-ups! :)